-- A executer dans Supabase SQL Editor
create table if not exists public.coque_modeles (
  id bigint generated by default as identity primary key,
  coque_id bigint not null references public.coques(id) on delete cascade,
  modele text not null,
  created_at timestamp with time zone default now(),
  unique(coque_id, modele)
);

create table if not exists public.commandes (
  id bigint generated by default as identity primary key,
  coque_id bigint references public.coques(id) on delete set null,
  modele text not null,
  nom text not null,
  prenom text not null,
  telephone text not null,
  adresse text not null,
  livraison text not null check (livraison in ('Bureau','Domicile','USTHB')),
  created_at timestamp with time zone default now()
);

create table if not exists public.avis (
  id bigint generated by default as identity primary key,
  commande_id bigint not null references public.commandes(id) on delete cascade,
  coque_id bigint references public.coques(id) on delete cascade,
  note integer not null check (note between 1 and 5),
  commentaire text,
  created_at timestamp with time zone default now(),
  unique(commande_id)
);

alter table public.coque_modeles enable row level security;
alter table public.commandes enable row level security;
alter table public.avis enable row level security;

drop policy if exists "Tout le monde peut voir les modeles" on public.coque_modeles;
create policy "Tout le monde peut voir les modeles" on public.coque_modeles for select using (true);

drop policy if exists "Tout le monde peut creer une commande" on public.commandes;
create policy "Tout le monde peut creer une commande" on public.commandes for insert with check (true);

drop policy if exists "Admin peut voir les commandes" on public.commandes;
create policy "Admin peut voir les commandes" on public.commandes for select using (auth.role() = 'authenticated');

drop policy if exists "Client peut voir sa commande par id" on public.commandes;
create policy "Client peut voir sa commande par id" on public.commandes for select using (true);

drop policy if exists "Tout le monde peut creer un avis" on public.avis;
create policy "Tout le monde peut creer un avis" on public.avis for insert with check (true);

drop policy if exists "Tout le monde peut voir les avis" on public.avis;
create policy "Tout le monde peut voir les avis" on public.avis for select using (true);

drop policy if exists "Admin peut modifier les commandes" on public.commandes;
create policy "Admin peut modifier les commandes" on public.commandes for update using (auth.role() = 'authenticated');

drop policy if exists "Admin peut supprimer les commandes" on public.commandes;
create policy "Admin peut supprimer les commandes" on public.commandes for delete using (auth.role() = 'authenticated');

-- Exemple : ajouter les modèles disponibles d'une coque
-- insert into public.coque_modeles(coque_id, modele) values (1,'iPhone 13'),(1,'iPhone 13 Pro');